management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: caixa.de.doacoes
    description: Projeto caixa de doacoes.
    author: Angelo Daiher
    version: '@project.version@'
spring:
  profiles:
    active: dev